### ISSUE TITLE
Absolute path

### ISSUE THREAD

**Issue by agdl** [Aftex2/License-Plate-Detection-with-OpenCV#2]
Code use absolute path with specific folders

**Comment by afeefabubakar** [comment]
Hello, thanks for commenting. For now, I've indicated where the path should be specified in the code. I'll try to find a more dynamic method of obtaining path later.

Edit: By the way, sorry for being late in replying. I don't open GitHub often and are still quite unfamiliar with it.

**Comment by vetrismash001** [comment]
i need complete guide for this project "Automatic number plate recognition of moving vehicles"...source code and step by step explanation from scratch to end of this project....help me to get this work( video tutorials)...

**Comment by vetrismash001** [comment]
contact me @vetri5cse@gmail.com (share the source materials you have been used ) can be any tutorials like videos on any platforms like udemy/....at any cost

**Comment by afeefabubakar** [comment]
#3 implemented relative path for saving folder. The `pytesseract.pytesseract.tesseract_cmd` (line 10) in anprclass.py still uses absolute path however as it will depend on user's installation path or PATH variables.
